# Copyright (c) 2019 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: download node_exporter
  shell: "{{ item }}"
  with_items:
    - curl -LO https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    - tar xvf node_exporter-0.17.0.linux-amd64.tar.gz
    - cp node_exporter-0.17.0.linux-amd64/node_exporter /usr/local/bin/
    - useradd --no-create-home --shell /bin/false node_exporter
    - chown node_exporter:node_exporter /usr/local/bin/node_exporter
  become: yes

- name: edit node_exporter.service
  shell: "{{ item }}"
  with_items:
    - bash ./script/set_node_exporter_service.sh
  become: yes

- name: start node_exporter
  shell: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl start node_exporter
  become: yes

- name: check status of node_exporter service
  shell: "{{ item }}"
  with_items:
    - systemctl status node_exporter
  become: yes
  
- name: configuring prometheus to scrape node_exporter
  shell: "{{ item }}"
  with_items:
    - bash ./script/mod_prometheus_config_for_node_exporter.sh
  become: yes

- name: restart prometheus
  shell: "{{ item }}"
  with_items:
    - systemctl restart prometheus
  become: yes

- name: check status of prometheus service
  shell: "{{ item }}"
  with_items:
    - systemctl status prometheus
  become: yes

